# Site specific settings
title: "Boulder Hack Night"
name: "Boulder Hack Night"
keywords: "Boulder Hack Night Tech"
baseurl: ""
url: "https://boulderhacknight.com"
description: "An aggressively unstructured, tech agnostic, soirée"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus:
twitter: bhacknight
facebook: 
github: spaceotterinspace
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
